In [ ]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [ ]:
# write your code here ^_^
x = np.random.randint(1,2, size = 7)
x

array([1, 1, 1, 1, 1, 1, 1])

## Q#2: Create y array with elements equal to 0.

In [ ]:
# write your code here ^_^
y = np.random.randint(1,size = 7)
y

array([0, 0, 0, 0, 0, 0, 0])

## Q#3: Add x and y arrays.

In [ ]:
# write your code here ^_^
x + y

array([1, 1, 1, 1, 1, 1, 1])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [ ]:
# write your code here ^_^
print(x.shape)
print(x.ndim)
print(x.size)
print(x.dtype)
print(x.data)

(7,)
1
7
int64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [ ]:
# write your code here ^_^
w = np.array([[11,12],[13,14],[15,16]])
print(w)

[[11 12]
 [13 14]
 [15 16]]


## Q#6: Create z array contains the numbers from 1 to 3.

In [ ]:
# write your code here ^_^
z = np.arange(1,4)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [ ]:
# write your code here ^_^
newArray = np.hstack((z.reshape(3,1),w))
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [ ]:
# write your code here ^_^
for row in newArray:
  print(row)
  for item in row:
    print(item)

[ 1 11 12]
1
11
12
[ 2 13 14]
2
13
14
[ 3 15 16]
3
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [ ]:
# write your code here ^_^
newArray.T

array([[ 1,  2,  3],
       [11, 13, 15],
       [12, 14, 16]])

## Q#10: Decrement all elements of "newArray" with 1.

In [ ]:
# write your code here ^_^
newArray = np.subtract(newArray, 1)
newArray

array([[ 0, 10, 11],
       [ 1, 12, 13],
       [ 2, 14, 15]])

## Q#11: Find smallest and biggest values in "newArray".

In [ ]:
# write your code here ^_^
print(newArray.min())
print(newArray.max())

0
15


## Q#12: Print the first row of "newArray" using indexing.

In [ ]:
# write your code here ^_^
print(newArray[0])

[ 0 10 11]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [ ]:
# write your code here ^_^
# assuming we don't have to automate finding it in the array:
print(newArray[1,1])

12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [ ]:
# write your code here ^_^
# assuming we don't have to automate finding it in the array:
print(newArray[0,0])
print(newArray[1,2])

0
13


## Q#15: Change the shape of "newArray" to (9,1).

In [ ]:
# write your code here ^_^
newArray.reshape(9,1)

array([[ 0],
       [10],
       [11],
       [ 1],
       [12],
       [13],
       [ 2],
       [14],
       [15]])

## Q#16: Change the shape of "newArray" to (3,2).

In [ ]:
# write your code here ^_^
# it cannot be reshaped into this because it contains 9 elements, which is too much for a 3X2 matrix.
newArray.reshape(3,2)

ValueError: cannot reshape array of size 9 into shape (3,2)

# Well Done 🎉