# -------------------------------------------------------------------------------------------------

# Name: Naif Saleh Ajeeb

# -------------------------------------------------------------------------------------------------

# Q1: Import numpy library


In [ ]:
# write your code here ^_^
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function


In [ ]:
# write your code here ^_^

sequence = np.linspace(0, 1, 15)
print(sequence)

[0.         0.07142857 0.14285714 0.21428571 0.28571429 0.35714286
 0.42857143 0.5        0.57142857 0.64285714 0.71428571 0.78571429
 0.85714286 0.92857143 1.        ]


# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below

Note : the array's name is up to you.

|      |      |      |      |
| ---- | ---- | ---- | ---- |
| arr1 | 1.1  | 2.1  | 3.1  |
| arr2 | 4.1  | 5.1  | 6.1  |
| arr3 | 7.1  | 8.1  | 9.1  |
| arr4 | 10.1 | 11.1 | 12.1 |


In [ ]:
# write your code here ^_^

arr = np.array([
    [1.1, 2.1, 3.1],
    [4.1, 5.1, 6.1],
    [7.1, 8.1, 9.1],
    [10.1, 11.1, 12.1]
])
arr = arr.reshape(2, 2, 3)

print(arr)

[[[ 1.1  2.1  3.1]
  [ 4.1  5.1  6.1]]

 [[ 7.1  8.1  9.1]
  [10.1 11.1 12.1]]]


# Q4: Print the following:

Note: use the same array from Q3.

- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.


In [ ]:
# write your code here ^_^
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.size)
print(arr.ndim)

<class 'numpy.ndarray'>
float64
(2, 2, 3)
12
3


# Q5: Change the array dimention from 3-D to 4-D

Note: use the same array from Q3.

- Create a new array to hold the changes.
- Print the new array's dimention and shape.


In [ ]:
# write your code here ^_^
arr = arr.reshape(2, 2, 3, 1)
print(arr)

[[[[ 1.1]
   [ 2.1]
   [ 3.1]]

  [[ 4.1]
   [ 5.1]
   [ 6.1]]]


 [[[ 7.1]
   [ 8.1]
   [ 9.1]]

  [[10.1]
   [11.1]
   [12.1]]]]


# Q6: Change the array's elements datatype to integer

Note: use the same array from Q5.

- Create a new array to hold the changes.
- Print the new array.


In [ ]:
# write your code here ^_^

arr = arr.astype(int)
print(arr)
print(arr.dtype)

[[[[ 1]
   [ 2]
   [ 3]]

  [[ 4]
   [ 5]
   [ 6]]]


 [[[ 7]
   [ 8]
   [ 9]]

  [[10]
   [11]
   [12]]]]
int32


# Q7: Print all array's elements using for loop

Note: use the same array from Q6.

Hint: use nditer()


In [ ]:
# write your code here ^_^

for x in np.nditer(arr):
    print(x)

# and this is my first instinct before I read the hint:

# for i in range(len(arr)):
#     for j in range(len(arr[i])):
#         print(arr[i][j])

1
2
3
4
5
6
7
8
9
10
11
12


# Q8: Print number 8 using array slicing

Note: use the same array from Q6.


In [ ]:
# write your code here ^_^

print(arr[1,0,1])

[8]


# Q9: Print number 5 and number 6 using array slicing

Note: use the same array from Q6.


In [ ]:
# write your code here ^_^
print(arr[0,1,1])
print(arr[0,1,2])


[5]
[6]


# Q10: Search for number 8 using where()

Note: use the same array from Q6.

Note: where() is only used with small data.

_the output represents the path of the index that leads to number 8_


In [ ]:
# write your code here ^_^

# i'm not sure if this is the right way to do it, but i can see that it returns the indices of lists leading to the value 8
# so i guess it's correct.
print(np.where(arr == 8))

(array([1], dtype=int64), array([0], dtype=int64), array([1], dtype=int64), array([0], dtype=int64))


# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])


Note: use the same array from Q6.


In [ ]:
# write your code here ^_^
arr = arr.reshape(2,3,2)
print(arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Q12: Join the given arrays below

    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])

## Q12.1: Join the arrays without specifying the axis


In [ ]:
# write your code here ^_^
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])
arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr3)

[['A' 'B']
 ['E' 'F']
 ['C' 'D']
 ['G' 'H']]


# Q12.2: Join the arrays along rows with axis = 1


In [ ]:
# write your code here ^_^
arr4 = np.concatenate((arr1, arr2), axis=1)
print(arr4)

[['A' 'B' 'C' 'D']
 ['E' 'F' 'G' 'H']]


# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays.

Note: use the same array from Q12.1


In [ ]:
# write your code here ^_^
arr4, arr5 = np.split(arr3,2, axis = 1)
print(arr4)
print(arr5)

[['A']
 ['E']
 ['C']
 ['G']]
[['B']
 ['F']
 ['D']
 ['H']]
